name: Deploy

on:
  push:
    branches:
      - master  # Change to your main branch if it's named differently

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.13.0'  # Use the version of Node.js you're working with

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          VITE_OPENAI_ORGANIZATION: ${{ secrets.VITE_OPENAI_ORGANIZATION }}
          VITE_OPENAI_API_KEY: ${{ secrets.VITE_OPENAI_API_KEY }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
